# Generated by Django 4.2.2 on 2024-09-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.UUIDField(null=True),
        ),
    ]
